image: eldeibiz/sfdxci:0.3
definitions:
  commonItems: &common
    echo "BITBUCKET_BRANCH=$BITBUCKET_BRANCH  -  BITBUCKET_TAG=$BITBUCKET_TAG  -  BITBUCKET_PR_DESTINATION_BRANCH=$BITBUCKET_PR_DESTINATION_BRANCH  -  BITBUCKET_DEPLOYMENT_ENVIRONMENT=$BITBUCKET_DEPLOYMENT_ENVIRONMENT" &&
    pwd &&
    TRUNK_REGEXP="^(dev|int|uat|pre|hot|pro)$" &&
    git fetch origin &&
    git checkout "${BITBUCKET_PR_DESTINATION_BRANCH:-dev}" &&
    git show-branch &&
    git checkout $BITBUCKET_BRANCH &&
    git show-branch | head -n30 &&
    CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD) &&
    PARENT_BRANCH=$(git show-branch | grep '^[^\[]*\*' | sed 's/.*\[\(.*\)\].*/\1/' | sed 's/[\^~].*//' | grep -v "$CURRENT_BRANCH" | head -n1) &&
    PARENT_TRUNK=$(git show-branch | grep '^[^\[]*\*' | sed 's/.*\[\(.*\)\].*/\1/' | sed 's/[\^~].*//' | grep -E "$TRUNK_REGEXP" | head -n1) &&
    DESTINATION_BRANCH=${BITBUCKET_PR_DESTINATION_BRANCH:-$PARENT_TRUNK} &&
    COMMIT_ANCESTOR=$(git merge-base --octopus HEAD $DESTINATION_BRANCH) &&
    echo "CURRENT_BRANCH=$CURRENT_BRANCH  -  PARENT_BRANCH=$PARENT_BRANCH  -  PARENT_TRUNK=$PARENT_TRUNK  -  DESTINATION_BRANCH=$DESTINATION_BRANCH  -  COMMIT_ANCESTOR=$COMMIT_ANCESTOR" &&
    mkdir -p .delta; sgd --to HEAD --from $COMMIT_ANCESTOR --repo . --output ./.delta &&
    cat .delta/package/package.xml &&
    cat .delta/destructiveChanges/destructiveChanges.xml 

pipelines:
  default: #These commands run for all branches unless specified otherwise
    - step: &diff_package
        name: "Default pipeline"
        deployment: dev
        script:
          - *common
          #- echo "BITBUCKET_BRANCH=$BITBUCKET_BRANCH  -  BITBUCKET_TAG=$BITBUCKET_TAG  -  BITBUCKET_PR_DESTINATION_BRANCH=$BITBUCKET_PR_DESTINATION_BRANCH  -  BITBUCKET_DEPLOYMENT_ENVIRONMENT=$BITBUCKET_DEPLOYMENT_ENVIRONMENT"
          #- pwd # Typical bitbucket dir: /opt/atlassian/pipelines/agent/build
          #- git fetch origin
          #- git checkout "${BITBUCKET_PR_DESTINATION_BRANCH:-dev}"
  branches :
    'feature/*':
      - step:
          name: "Branch pipeline for features"
          deployment: dev
          script:
          - echo "BITBUCKET_BRANCH=$BITBUCKET_BRANCH  -  BITBUCKET_TAG=$BITBUCKET_TAG  -  BITBUCKET_PR_DESTINATION_BRANCH=$BITBUCKET_PR_DESTINATION_BRANCH  -  BITBUCKET_DEPLOYMENT_ENVIRONMENT=$BITBUCKET_DEPLOYMENT_ENVIRONMENT"
          # Bajar información de la rama remota dev, ya que bitbucket sólo baja de la rama actual: git clone --branch="feature/US-00001-Span" --depth 50 https://dvdjg@bitbucket.org/dvdjg/devops.git
          - git remote set-branches origin 'dev' # usar 'dev' para bajar info sólo de dev o '*' para bajarlo todo
          - git fetch -v
          - DESTINATION_BRANCH=dev
          - git checkout $DESTINATION_BRANCH
          - git checkout $BITBUCKET_BRANCH
          - COMMIT_ANCESTOR=$(git merge-base --octopus HEAD $DESTINATION_BRANCH)
          - echo "DESTINATION_BRANCH=$DESTINATION_BRANCH  -  COMMIT_ANCESTOR=$COMMIT_ANCESTOR"
          - mkdir -p .delta; sgd --to HEAD --from $COMMIT_ANCESTOR --repo . --output ./.delta
          - cat .delta/package/package.xml
          - cat .delta/destructiveChanges/destructiveChanges.xml
    dev:
      - step:
          name: "Branch pipeline for dev"
          deployment: dev
          script:
          # Typical bitbucket dir: /opt/atlassian/pipelines/agent/build
          - echo "BITBUCKET_BRANCH=$BITBUCKET_BRANCH  -  BITBUCKET_TAG=$BITBUCKET_TAG  -  BITBUCKET_PR_DESTINATION_BRANCH=$BITBUCKET_PR_DESTINATION_BRANCH  -  BITBUCKET_DEPLOYMENT_ENVIRONMENT=$BITBUCKET_DEPLOYMENT_ENVIRONMENT"
          - TRUNK_REGEXP="^(dev|int|uat|pre|hot|pro)$"
          - git fetch origin
          - git checkout "${BITBUCKET_PR_DESTINATION_BRANCH:-dev}"
          - git show-branch
          - git checkout $BITBUCKET_BRANCH
          - git show-branch | head -n30
          - CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          - PARENT_BRANCH=$(git show-branch | grep '^[^\[]*\*' | sed 's/.*\[\(.*\)\].*/\1/' | sed 's/[\^~].*//' | grep -v "$CURRENT_BRANCH" | head -n1)
          - PARENT_TRUNK=$(git show-branch | grep '^[^\[]*\*' | sed 's/.*\[\(.*\)\].*/\1/' | sed 's/[\^~].*//' | grep -E "$TRUNK_REGEXP" | head -n1)
          - DESTINATION_BRANCH=${BITBUCKET_PR_DESTINATION_BRANCH:-$PARENT_TRUNK}
          - COMMIT_ANCESTOR=$(git merge-base --octopus HEAD $DESTINATION_BRANCH)
          - echo "CURRENT_BRANCH=$CURRENT_BRANCH  -  PARENT_BRANCH=$PARENT_BRANCH  -  PARENT_TRUNK=$PARENT_TRUNK  -  DESTINATION_BRANCH=$DESTINATION_BRANCH  -  COMMIT_ANCESTOR=$COMMIT_ANCESTOR"
          - mkdir -p .delta; sgd --to HEAD --from $COMMIT_ANCESTOR --repo . --output ./.delta
          - cat .delta/package/package.xml
          - cat .delta/destructiveChanges/destructiveChanges.xml

          # By default, the CLI periodically checks for and installs updates.
          # Disable (true) this auto-update check to improve performance of CLI commands.
          - export SFDX_AUTOUPDATE_DISABLE=true

          # Specifies the time, in seconds, that the CLI waits for the Lightning Experience custom domain to resolve and become available in a newly-created scratch org.
          # If you get errors about My Domain not configured when you try to use a newly-created scratch org, increase this wait time.
          - export SFDX_DOMAIN_RETRY=300

          # For force:package:create, disables automatic updates to the sfdx-project.json file.
          - export SFDX_PROJECT_AUTOUPDATE_DISABLE_FOR_PACKAGE_CREATE=true

          # For force:package:version:create, disables automatic updates to the sfdx-project.json file.
          - export SFDX_PROJECT_AUTOUPDATE_DISABLE_FOR_PACKAGE_VERSION_CREATE=true

          - export TESTLEVEL=RunLocalTests

          # Current variables
          - echo $SFDC_PRO_URL
          - echo $SFDC_PRO_USER

          # Output CLI version and plug-in information
          - sfdx --version
          - sfdx plugins --core

          #Decrypt server key
          - openssl enc -nosalt -aes-256-cbc -d -in ./assets/server.key.enc -out server.key -base64 -K $DECRYPTION_KEY -iv $DECRYPTION_IV

          - sfdx force:auth:jwt:grant --clientid $CONSUMER_KEY --username $SFDC_PRO_USER --jwtkeyfile server.key --setdefaultdevhubusername --setalias sfdx-ci --instanceurl $SFDC_PRO_URL
          - sfdx force:limits:api:display -u $SFDC_PRO_USER
          - sfdx force:source:convert -d mdapi --manifest .delta/package/package.xml

          - | # Show computed package
            [ -f mdapi/package.xml ] && cat mdapi/package.xml
          - sfdx force:mdapi:deploy -d mdapi -u $SFDC_PRO_USER -w 30 --testlevel $TESTLEVEL --loglevel fatal -l RunLocalTests
        
    dev-scratch:
      - step:
          name: "Branch pipeline for create a scratch org in dev"
          deployment: dev
          script:
          - echo "BITBUCKET_BRANCH=$BITBUCKET_BRANCH  -  BITBUCKET_TAG=$BITBUCKET_TAG  -  BITBUCKET_PR_DESTINATION_BRANCH=$BITBUCKET_PR_DESTINATION_BRANCH  -  BITBUCKET_DEPLOYMENT_ENVIRONMENT=$BITBUCKET_DEPLOYMENT_ENVIRONMENT"
          #Decrypt server key
          - openssl enc -nosalt -aes-256-cbc -d -in ./assets/server.key.enc -out server.key -base64 -K $DECRYPTION_KEY -iv $DECRYPTION_IV

          - sfdx force:auth:jwt:grant --clientid $CONSUMER_KEY --username $SFDC_PRO_USER --jwtkeyfile server.key --setdefaultdevhubusername --setalias sfdx-ci --instanceurl $SFDC_PRO_URL
          - sfdx force:limits:api:display -u $SFDC_PRO_USER
          # Create a scratch org, set it as your default, and give it an alias
          - sfdx force:org:create -s -f config/project-scratch-def.json -a scratch-org
          # Display navigation URL, but don’t launch browser.
          - sfdx force:org:open -r 
          - sfdx force:org:display --verbose --json
          # Install Financial Services Cloud - https://help.salesforce.com/s/articleView?id=000323341&type=1
          - sfdx force:package:install --package=04t1E000000jbFt --wait 20 --publishwait 20 --noprompt --securitytype AllUsers
          # Install Financial Services Ext
          - sfdx force:package:install --package=04t1E000001Iql5 --wait 20 --publishwait 20 --noprompt --securitytype AllUsers
          # FSC Post-Installation Tasks: https://developer.salesforce.com/docs/atlas.en-us.financial_services_cloud.meta/financial_services_cloud/fsc_admin_postinstall_tasks.htm
          # Push source metadata to Scratch Org
          - sfdx force:source:push
          # echo "Importing sample data..."
          - sfdx force:data:tree:import -p data/basic/basic-Account-Contact-Case-Opportunity-plan.json -u scratch-org

  pull-requests:
    'feature/*': # Pull request from feature branch to Trunk
      - step:
          name: "Trunk Pull Request Validate Package"
          deployment: dev
          script:
          # Typical bitbucket dir: /opt/atlassian/pipelines/agent/build
          - echo "BITBUCKET_BRANCH=$BITBUCKET_BRANCH  -  BITBUCKET_TAG=$BITBUCKET_TAG  -  BITBUCKET_PR_DESTINATION_BRANCH=$BITBUCKET_PR_DESTINATION_BRANCH  -  BITBUCKET_DEPLOYMENT_ENVIRONMENT=$BITBUCKET_DEPLOYMENT_ENVIRONMENT"
          - TRUNK_REGEXP="^(dev|int|uat|pre|hot|pro)$"
          - git fetch origin
          - git checkout "${BITBUCKET_PR_DESTINATION_BRANCH:-dev}"
          - git show-branch
          - git checkout $BITBUCKET_BRANCH
          - git show-branch | head -n30
          - CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          - PARENT_BRANCH=$(git show-branch | grep '^[^\[]*\*' | sed 's/.*\[\(.*\)\].*/\1/' | sed 's/[\^~].*//' | grep -v "$CURRENT_BRANCH" | head -n1)
          - PARENT_TRUNK=$(git show-branch | grep '^[^\[]*\*' | sed 's/.*\[\(.*\)\].*/\1/' | sed 's/[\^~].*//' | grep -E "$TRUNK_REGEXP" | head -n1)
          - DESTINATION_BRANCH=${BITBUCKET_PR_DESTINATION_BRANCH:-$PARENT_TRUNK}
          - COMMIT_ANCESTOR=$(git merge-base --octopus HEAD $DESTINATION_BRANCH)
          - echo "CURRENT_BRANCH=$CURRENT_BRANCH  -  PARENT_BRANCH=$PARENT_BRANCH  -  PARENT_TRUNK=$PARENT_TRUNK  -  DESTINATION_BRANCH=$DESTINATION_BRANCH  -  COMMIT_ANCESTOR=$COMMIT_ANCESTOR"
          - mkdir -p .delta; sgd --to HEAD --from $COMMIT_ANCESTOR --repo . --output ./.delta
          - cat .delta/package/package.xml
          - cat .delta/destructiveChanges/destructiveChanges.xml

          # By default, the CLI periodically checks for and installs updates.
          # Disable (true) this auto-update check to improve performance of CLI commands.
          - export SFDX_AUTOUPDATE_DISABLE=true

          # Specifies the time, in seconds, that the CLI waits for the Lightning Experience custom domain to resolve and become available in a newly-created scratch org.
          # If you get errors about My Domain not configured when you try to use a newly-created scratch org, increase this wait time.
          - export SFDX_DOMAIN_RETRY=300

          # For force:package:create, disables automatic updates to the sfdx-project.json file.
          - export SFDX_PROJECT_AUTOUPDATE_DISABLE_FOR_PACKAGE_CREATE=true

          # For force:package:version:create, disables automatic updates to the sfdx-project.json file.
          - export SFDX_PROJECT_AUTOUPDATE_DISABLE_FOR_PACKAGE_VERSION_CREATE=true

          - export TESTLEVEL=RunLocalTests

          # Current variables
          - echo $SFDC_PRO_URL
          - echo $SFDC_PRO_USER

          # Output CLI version and plug-in information
          - sfdx --version
          - sfdx plugins --core

          #Decrypt server key
          - openssl enc -nosalt -aes-256-cbc -d -in ./assets/server.key.enc -out server.key -base64 -K $DECRYPTION_KEY -iv $DECRYPTION_IV

          - sfdx force:auth:jwt:grant --clientid $CONSUMER_KEY --username $SFDC_PRO_USER --jwtkeyfile server.key --setdefaultdevhubusername --setalias sfdx-ci --instanceurl $SFDC_PRO_URL
          - sfdx force:limits:api:display -u $SFDC_PRO_USER
          - sfdx force:source:convert --outputdir mdapi --manifest .delta/package/package.xml

          - | # Show computed package
            [ -f mdapi/package.xml ] && cat mdapi/package.xml
          # After the validation, a deploy can be accelerated by using quick deploy: --validateddeployrequestid <VALIDATEDDEPLOYREQUESTID>
          - sfdx force:mdapi:deploy -d mdapi -u $SFDC_PRO_USER -w 30 --testlevel $TESTLEVEL --loglevel fatal -l RunLocalTests --checkonly 
          # sfdx force:source:deploy -q 0Af9A00000FTM6pSAH
          
          after-script:
          - sfdx auth:logout --all --noprompt
